In [186]:
import pandas as pd

In [187]:
data = "post_pandemic_remote_work_health_impact_2025.csv"

post_pandemic_df = pd.read_csv(data)

post_pandemic_df.head()

,Survey_Date,Age,Gender,Region,Industry,Job_Role,Work_Arrangement,Hours_Per_Week,Mental_Health_Status,Burnout_Level,Work_Life_Balance_Score,Physical_Health_Issues,Social_Isolation_Score,Salary_Range
0,2025-06-01,27,Female,Asia,Professional Services,Data Analyst,Onsite,64,Stress Disorder,High,3,Shoulder Pain; Neck Pain,2,$40K-60K
1,2025-06-01,37,Female,Asia,Professional Services,Data Analyst,Onsite,37,Stress Disorder,High,4,Back Pain,2,$80K-100K
2,2025-06-01,32,Female,Africa,Education,Business Analyst,Onsite,36,ADHD,High,3,Shoulder Pain; Eye Strain,2,$80K-100K
3,2025-06-01,40,Female,Europe,Education,Data Analyst,Onsite,63,ADHD,Medium,1,Shoulder Pain; Eye Strain,2,$60K-80K
4,2025-06-01,30,Male,South America,Manufacturing,DevOps Engineer,Hybrid,65,NaN,Medium,5,NaN,4,$60K-80K

Dataset overview

In [188]:
post_pandemic_df.describe()

,Age,Hours_Per_Week,Work_Life_Balance_Score,Social_Isolation_Score
count,3157.000000,3157.000000,3157.000000,3157.000000
mean,43.732024,49.904973,2.996516,2.704783
std,12.661095,8.897699,1.163307,1.188887
min,22.000000,35.000000,1.000000,1.000000
25%,33.000000,42.000000,2.000000,2.000000
50%,44.000000,50.000000,3.000000,3.000000
75%,55.000000,57.000000,4.000000,4.000000
max,65.000000,65.000000,5.000000,5.000000

In [189]:
post_pandemic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3157 entries, 0 to 3156
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Survey_Date              3157 non-null   object
 1   Age                      3157 non-null   int64
 2   Gender                   3157 non-null   object
 3   Region                   3157 non-null   object
 4   Industry                 3157 non-null   object
 5   Job_Role                 3157 non-null   object
 6   Work_Arrangement         3157 non-null   object
 7   Hours_Per_Week           3157 non-null   int64
 8   Mental_Health_Status     2358 non-null   object
 9   Burnout_Level            3157 non-null   object
 10  Work_Life_Balance_Score  3157 non-null   int64
 11  Physical_Health_Issues   2877 non-null   object
 12  Social_Isolation_Score   3157 non-null   int64
 13  Salary_Range             3157 non-null   object
dtypes: int64(4), object(10)
memory usage: 345.4+ KB

In [190]:
post_pandemic_df.shape

(3157, 14)

In [191]:
#Missing Values 

post_pandemic_df.isnull().sum()

Survey_Date                  0
Age                          0
Gender                       0
Region                       0
Industry                     0
Job_Role                     0
Work_Arrangement             0
Hours_Per_Week               0
Mental_Health_Status       799
Burnout_Level                0
Work_Life_Balance_Score      0
Physical_Health_Issues     280
Social_Isolation_Score       0
Salary_Range                 0
dtype: int64

In [192]:
# Duplicate value

post_pandemic_df.duplicated().sum()

0

In [193]:
post_pandemic_df["Physical_Health_Issues"].value_counts(dropna=False)

Physical_Health_Issues
NaN                                                            280
Shoulder Pain; Eye Strain                                      262
Back Pain; Eye Strain                                          258
Eye Strain                                                     256
Back Pain; Shoulder Pain; Eye Strain                           255
Back Pain                                                      253
Shoulder Pain                                                  235
Back Pain; Shoulder Pain                                       218
Back Pain; Eye Strain; Neck Pain                                93
Neck Pain                                                       92
Eye Strain; Neck Pain                                           90
Back Pain; Neck Pain                                            88
Back Pain; Shoulder Pain; Eye Strain; Neck Pain                 88
Shoulder Pain; Neck Pain                                        78
Shoulder Pain; Eye Strain; Neck Pain                            76
Back Pain; Shoulder Pain; Neck Pain                             68
Back Pain; Shoulder Pain; Eye Strain; Wrist Pain                51
Wrist Pain                                                      49
Back Pain; Wrist Pain                                           46
Eye Strain; Wrist Pain                                          43
Back Pain; Shoulder Pain; Wrist Pain                            41
Shoulder Pain; Wrist Pain                                       38
Shoulder Pain; Eye Strain; Wrist Pain                           38
Back Pain; Eye Strain; Wrist Pain                               36
Neck Pain; Wrist Pain                                           23
Back Pain; Shoulder Pain; Neck Pain; Wrist Pain                 19
Back Pain; Shoulder Pain; Eye Strain; Neck Pain; Wrist Pain     18
Back Pain; Eye Strain; Neck Pain; Wrist Pain                    17
Back Pain; Neck Pain; Wrist Pain                                14
Eye Strain; Neck Pain; Wrist Pain                               12
Shoulder Pain; Eye Strain; Neck Pain; Wrist Pain                11
Shoulder Pain; Neck Pain; Wrist Pain                            11
Name: count, dtype: int64

## Data cleaning

##### I didn't think dropping the null values would make sense because it could be those people didn't experience any Physical health issues and/or Mental Health issues.

In [194]:
post_pandemic_df["Physical_Health_Issues"] = post_pandemic_df["Physical_Health_Issues"].fillna("None")
post_pandemic_df["Physical_Health_Issues"] = post_pandemic_df["Physical_Health_Issues"].replace(r'^\s*$', "None", regex=True)

post_pandemic_df["Physical_Health_Issues"].value_counts()

Physical_Health_Issues
None                                                           280
Shoulder Pain; Eye Strain                                      262
Back Pain; Eye Strain                                          258
Eye Strain                                                     256
Back Pain; Shoulder Pain; Eye Strain                           255
Back Pain                                                      253
Shoulder Pain                                                  235
Back Pain; Shoulder Pain                                       218
Back Pain; Eye Strain; Neck Pain                                93
Neck Pain                                                       92
Eye Strain; Neck Pain                                           90
Back Pain; Neck Pain                                            88
Back Pain; Shoulder Pain; Eye Strain; Neck Pain                 88
Shoulder Pain; Neck Pain                                        78
Shoulder Pain; Eye Strain; Neck Pain                            76
Back Pain; Shoulder Pain; Neck Pain                             68
Back Pain; Shoulder Pain; Eye Strain; Wrist Pain                51
Wrist Pain                                                      49
Back Pain; Wrist Pain                                           46
Eye Strain; Wrist Pain                                          43
Back Pain; Shoulder Pain; Wrist Pain                            41
Shoulder Pain; Wrist Pain                                       38
Shoulder Pain; Eye Strain; Wrist Pain                           38
Back Pain; Eye Strain; Wrist Pain                               36
Neck Pain; Wrist Pain                                           23
Back Pain; Shoulder Pain; Neck Pain; Wrist Pain                 19
Back Pain; Shoulder Pain; Eye Strain; Neck Pain; Wrist Pain     18
Back Pain; Eye Strain; Neck Pain; Wrist Pain                    17
Back Pain; Neck Pain; Wrist Pain                                14
Eye Strain; Neck Pain; Wrist Pain                               12
Shoulder Pain; Eye Strain; Neck Pain; Wrist Pain                11
Shoulder Pain; Neck Pain; Wrist Pain                            11
Name: count, dtype: int64

In [195]:
post_pandemic_df['Mental_Health_Status'] = post_pandemic_df['Mental_Health_Status'].fillna("None")
post_pandemic_df['Mental_Health_Status'] = post_pandemic_df['Mental_Health_Status'].replace(r'^\s*$', "None", regex=True)

post_pandemic_df['Mental_Health_Status'].value_counts()

Mental_Health_Status
None               799
PTSD               423
Anxiety            394
Burnout            392
Depression         386
ADHD               385
Stress Disorder    378
Name: count, dtype: int64

## Exploding the Physical Health Issue column because is have 2 or more value in a single cell, which is against the normalization rule.

In [196]:
#Creating a unique id for the dataset
post_pandemic_df = post_pandemic_df.reset_index(drop=True)

post_pandemic_df['Person_ID'] = post_pandemic_df.index + 1

post_pandemic_df.head()

,Survey_Date,Age,Gender,Region,Industry,Job_Role,Work_Arrangement,Hours_Per_Week,Mental_Health_Status,Burnout_Level,Work_Life_Balance_Score,Physical_Health_Issues,Social_Isolation_Score,Salary_Range,Person_ID
0,2025-06-01,27,Female,Asia,Professional Services,Data Analyst,Onsite,64,Stress Disorder,High,3,Shoulder Pain; Neck Pain,2,$40K-60K,1
1,2025-06-01,37,Female,Asia,Professional Services,Data Analyst,Onsite,37,Stress Disorder,High,4,Back Pain,2,$80K-100K,2
2,2025-06-01,32,Female,Africa,Education,Business Analyst,Onsite,36,ADHD,High,3,Shoulder Pain; Eye Strain,2,$80K-100K,3
3,2025-06-01,40,Female,Europe,Education,Data Analyst,Onsite,63,ADHD,Medium,1,Shoulder Pain; Eye Strain,2,$60K-80K,4
4,2025-06-01,30,Male,South America,Manufacturing,DevOps Engineer,Hybrid,65,None,Medium,5,None,4,$60K-80K,5

In [197]:
# 1. Pop the column out of the DataFrame
col = post_pandemic_df.pop('Person_ID')

# 2. Insert it back at index 0 (the first position)
post_pandemic_df.insert(0, 'Person_ID', col)

In [198]:
# Split multiple health issues
post_pandemic_df['Physical_Health_Issues'] = post_pandemic_df['Physical_Health_Issues'].str.split(';')

post_pandemic_df.head()

,Person_ID,Survey_Date,Age,Gender,Region,Industry,Job_Role,Work_Arrangement,Hours_Per_Week,Mental_Health_Status,Burnout_Level,Work_Life_Balance_Score,Physical_Health_Issues,Social_Isolation_Score,Salary_Range
0,1,2025-06-01,27,Female,Asia,Professional Services,Data Analyst,Onsite,64,Stress Disorder,High,3,"[Shoulder Pain, Neck Pain]",2,$40K-60K
1,2,2025-06-01,37,Female,Asia,Professional Services,Data Analyst,Onsite,37,Stress Disorder,High,4,[Back Pain],2,$80K-100K
2,3,2025-06-01,32,Female,Africa,Education,Business Analyst,Onsite,36,ADHD,High,3,"[Shoulder Pain, Eye Strain]",2,$80K-100K
3,4,2025-06-01,40,Female,Europe,Education,Data Analyst,Onsite,63,ADHD,Medium,1,"[Shoulder Pain, Eye Strain]",2,$60K-80K
4,5,2025-06-01,30,Male,South America,Manufacturing,DevOps Engineer,Hybrid,65,None,Medium,5,[None],4,$60K-80K

In [199]:
post_pandemic_df['Physical_Health_Issues'] = post_pandemic_df['Physical_Health_Issues'].apply(
    lambda x: [i.strip() for i in x] if isinstance(x, list) else x
)
post_pandemic_df.head()

,Person_ID,Survey_Date,Age,Gender,Region,Industry,Job_Role,Work_Arrangement,Hours_Per_Week,Mental_Health_Status,Burnout_Level,Work_Life_Balance_Score,Physical_Health_Issues,Social_Isolation_Score,Salary_Range
0,1,2025-06-01,27,Female,Asia,Professional Services,Data Analyst,Onsite,64,Stress Disorder,High,3,"[Shoulder Pain, Neck Pain]",2,$40K-60K
1,2,2025-06-01,37,Female,Asia,Professional Services,Data Analyst,Onsite,37,Stress Disorder,High,4,[Back Pain],2,$80K-100K
2,3,2025-06-01,32,Female,Africa,Education,Business Analyst,Onsite,36,ADHD,High,3,"[Shoulder Pain, Eye Strain]",2,$80K-100K
3,4,2025-06-01,40,Female,Europe,Education,Data Analyst,Onsite,63,ADHD,Medium,1,"[Shoulder Pain, Eye Strain]",2,$60K-80K
4,5,2025-06-01,30,Male,South America,Manufacturing,DevOps Engineer,Hybrid,65,None,Medium,5,[None],4,$60K-80K

In [200]:
post_pandemic_df = post_pandemic_df.explode('Physical_Health_Issues')

post_pandemic_df.head()

,Person_ID,Survey_Date,Age,Gender,Region,Industry,Job_Role,Work_Arrangement,Hours_Per_Week,Mental_Health_Status,Burnout_Level,Work_Life_Balance_Score,Physical_Health_Issues,Social_Isolation_Score,Salary_Range
0,1,2025-06-01,27,Female,Asia,Professional Services,Data Analyst,Onsite,64,Stress Disorder,High,3,Shoulder Pain,2,$40K-60K
0,1,2025-06-01,27,Female,Asia,Professional Services,Data Analyst,Onsite,64,Stress Disorder,High,3,Neck Pain,2,$40K-60K
1,2,2025-06-01,37,Female,Asia,Professional Services,Data Analyst,Onsite,37,Stress Disorder,High,4,Back Pain,2,$80K-100K
2,3,2025-06-01,32,Female,Africa,Education,Business Analyst,Onsite,36,ADHD,High,3,Shoulder Pain,2,$80K-100K
2,3,2025-06-01,32,Female,Africa,Education,Business Analyst,Onsite,36,ADHD,High,3,Eye Strain,2,$80K-100K

## Changing the datatype for Survey_Date to date

In [201]:
post_pandemic_df['Survey_Date'] = pd.to_datetime(post_pandemic_df['Survey_Date'])

post_pandemic_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6219 entries, 0 to 3156
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person_ID                6219 non-null   int64
 1   Survey_Date              6219 non-null   datetime64[ns]
 2   Age                      6219 non-null   int64
 3   Gender                   6219 non-null   object
 4   Region                   6219 non-null   object
 5   Industry                 6219 non-null   object
 6   Job_Role                 6219 non-null   object
 7   Work_Arrangement         6219 non-null   object
 8   Hours_Per_Week           6219 non-null   int64
 9   Mental_Health_Status     6219 non-null   object
 10  Burnout_Level            6219 non-null   object
 11  Work_Life_Balance_Score  6219 non-null   int64
 12  Physical_Health_Issues   6219 non-null   object
 13  Social_Isolation_Score   6219 non-null   int64
 14  Salary_Range             6219 non-null   object
dtypes: datetime64[ns](1), int64(5), object(9)
memory usage: 777.4+ KB

## Standardizing the columns

In [202]:
col = post_pandemic_df.columns
col

Index(['Person_ID', 'Survey_Date', 'Age', 'Gender', 'Region', 'Industry',
       'Job_Role', 'Work_Arrangement', 'Hours_Per_Week',
       'Mental_Health_Status', 'Burnout_Level', 'Work_Life_Balance_Score',
       'Physical_Health_Issues', 'Social_Isolation_Score', 'Salary_Range'],
      dtype='object')

In [203]:
post_pandemic_df.columns = [col.lower() for col in post_pandemic_df.columns]

post_pandemic_df.head()

,person_id,survey_date,age,gender,region,industry,job_role,work_arrangement,hours_per_week,mental_health_status,burnout_level,work_life_balance_score,physical_health_issues,social_isolation_score,salary_range
0,1,2025-06-01,27,Female,Asia,Professional Services,Data Analyst,Onsite,64,Stress Disorder,High,3,Shoulder Pain,2,$40K-60K
0,1,2025-06-01,27,Female,Asia,Professional Services,Data Analyst,Onsite,64,Stress Disorder,High,3,Neck Pain,2,$40K-60K
1,2,2025-06-01,37,Female,Asia,Professional Services,Data Analyst,Onsite,37,Stress Disorder,High,4,Back Pain,2,$80K-100K
2,3,2025-06-01,32,Female,Africa,Education,Business Analyst,Onsite,36,ADHD,High,3,Shoulder Pain,2,$80K-100K
2,3,2025-06-01,32,Female,Africa,Education,Business Analyst,Onsite,36,ADHD,High,3,Eye Strain,2,$80K-100K

In [204]:
post_pandemic_df.shape

(6219, 15)

## FEATURE ENGINEERING

In [205]:
# AGE GROUP RANGE

print(min(post_pandemic_df['age']))

print(max(post_pandemic_df['age']))

22
65

In [206]:

post_pandemic_df['age_range'] = pd.cut(post_pandemic_df['age'],
                                       bins= [20, 30, 40, 50, 60, float('inf')],
                                       labels = ['20-30', '31-40', '41-50', '51-60', '61+'])

post_pandemic_df

,person_id,survey_date,age,gender,region,industry,job_role,work_arrangement,hours_per_week,mental_health_status,burnout_level,work_life_balance_score,physical_health_issues,social_isolation_score,salary_range,age_range
0,1,2025-06-01,27,Female,Asia,Professional Services,Data Analyst,Onsite,64,Stress Disorder,High,3,Shoulder Pain,2,$40K-60K,20-30
0,1,2025-06-01,27,Female,Asia,Professional Services,Data Analyst,Onsite,64,Stress Disorder,High,3,Neck Pain,2,$40K-60K,20-30
1,2,2025-06-01,37,Female,Asia,Professional Services,Data Analyst,Onsite,37,Stress Disorder,High,4,Back Pain,2,$80K-100K,31-40
2,3,2025-06-01,32,Female,Africa,Education,Business Analyst,Onsite,36,ADHD,High,3,Shoulder Pain,2,$80K-100K,31-40
2,3,2025-06-01,32,Female,Africa,Education,Business Analyst,Onsite,36,ADHD,High,3,Eye Strain,2,$80K-100K,31-40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3155,3156,2025-06-26,38,Male,North America,Education,Operations Manager,Onsite,52,Depression,Medium,3,Shoulder Pain,5,$80K-100K,31-40
3155,3156,2025-06-26,38,Male,North America,Education,Operations Manager,Onsite,52,Depression,Medium,3,Eye Strain,5,$80K-100K,31-40
3155,3156,2025-06-26,38,Male,North America,Education,Operations Manager,Onsite,52,Depression,Medium,3,Neck Pain,5,$80K-100K,31-40
3156,3157,2025-06-26,54,Female,North America,Healthcare,Technical Writer,Onsite,39,Burnout,Medium,4,Back Pain,2,$100K-120K,51-60
3156,3157,2025-06-26,54,Female,North America,Healthcare,Technical Writer,Onsite,39,Burnout,Medium,4,Eye Strain,2,$100K-120K,51-60

## Saving the clean up dataset file

In [207]:
post_pandemic_df.to_csv('Post Pandemic Dataset', index=False)